# Generated by Django 4.0.3 on 2022-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_reader_readpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.EmailField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
