# Generated by Django 4.0.3 on 2022-04-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
        ('reader', '0004_alter_reader_readpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='readpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.readpoint'),
        ),
    ]
