# Generated by Django 4.0.3 on 2022-04-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_alter_reader_type_reader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
