# Generated by Django 4.0.3 on 2022-05-06 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
        ('reader', '0007_delete_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='readpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.readpoint'),
        ),
    ]
