# Generated by Django 4.0.3 on 2022-05-14 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
        ('reader', '0008_alter_reader_readpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_frequentation', models.DateField(auto_now=True)),
                ('lecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('readpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.readpoint')),
            ],
        ),
    ]
