# Generated by Django 4.0.3 on 2022-05-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_frequentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentation',
            name='mois',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='frequentation',
            name='semaine',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='frequentation',
            name='date_frequentation',
            field=models.IntegerField(default=2022),
        ),
    ]
