# Generated by Django 4.0.4 on 2022-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_frequentation_mois_frequentation_semaine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentation',
            name='semaine',
            field=models.IntegerField(default=21),
        ),
    ]
