# Generated by Django 4.0.3 on 2022-05-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
        ('siteweb', '0002_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='readpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.readpoint'),
            preserve_default=False,
        ),
    ]
