# Generated by Django 4.0.3 on 2022-05-12 03:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_site_front', '0003_commentaires_echo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaires_echo',
            new_name='Commentaires_eco',
        ),
    ]
