# Generated by Django 4.0.4 on 2022-05-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site_front', '0004_rename_commentaires_echo_commentaires_eco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaires',
        ),
    ]
